# Generated by Django 5.2.15 on 2026-07-06 18:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db_core', '0001_baseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('display_name', models.TextField()),
                ('principal_party_id', models.UUIDField(blank=True, null=True)),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'security"."app_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('party_type', models.TextField()),
                ('display_name', models.TextField()),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'identity"."party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('party', models.OneToOneField(db_column='party_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='organization', serialize=False, to='db_core.party')),
                ('organization_type', models.TextField()),
                ('legal_name', models.TextField()),
                ('legal_form', models.TextField(blank=True, null=True)),
                ('registration_number', models.TextField(blank=True, null=True)),
                ('tax_number', models.TextField(blank=True, null=True)),
                ('vat_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity"."organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('party', models.OneToOneField(db_column='party_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='person', serialize=False, to='db_core.party')),
                ('salutation', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity"."person',
                'managed': False,
            },
        ),
    ]
