# Generated by Django 5.2.15 on 2026-07-08 08:36

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('house_number', models.TextField(blank=True, null=True)),
                ('address_addition', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField()),
                ('city', models.TextField()),
                ('country_code', models.CharField(db_default='DE', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'identity"."address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('building_number', models.TextField()),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('property_number', models.TextField(db_default=db_core.models.PropertyNumberDefault())),
                ('name', models.TextField()),
                ('property_type', models.TextField()),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyPartyRole',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."property_party_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('unit_type', models.TextField()),
                ('unit_number', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."unit',
                'managed': False,
            },
        ),
    ]
