# Generated by Django 5.2.15 on 2026-07-08 13:42

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0003_address_building_property_propertypartyrole_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('project_number', models.TextField(db_default=db_core.models.ProjectNumberDefault())),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('color_hex', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField()),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."project_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectProperty',
            fields=[
                ('pk', models.CompositePrimaryKey('project_id', 'property_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."project_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCase',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('case_number', models.TextField(db_default=db_core.models.ServiceCaseNumberDefault())),
                ('subject', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('responsibility_scope', models.TextField()),
                ('priority', models.TextField()),
                ('status', models.TextField()),
                ('received_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."service_case',
                'managed': False,
            },
        ),
    ]
