# Generated by Django 5.2.15 on 2026-07-08 15:33

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quote_number', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('status', models.TextField()),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('valid_until_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(db_default='EUR', max_length=3)),
                ('net_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."quote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position_number', models.IntegerField()),
                ('line_type', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('tax_rate_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."quote_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mandatory_text', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('stb_confirmed_at', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."tax_code',
                'managed': False,
            },
        ),
    ]
