# Generated by Django 5.2.15 on 2026-07-08 15:53

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0007_quote_quoteline_taxcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('article_number', models.TextField()),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True, null=True)),
                ('gtin', models.TextField(blank=True, null=True)),
                ('manufacturer_name', models.TextField(blank=True, null=True)),
                ('manufacturer_number', models.TextField(blank=True, null=True)),
                ('unit', models.TextField()),
                ('line_type', models.TextField()),
                ('product_group', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('assembly_number', models.TextField()),
                ('name', models.TextField()),
                ('internal_name', models.TextField(blank=True, null=True)),
                ('unit', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."assembly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."assembly_component',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WageGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('kind', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."wage_group',
                'managed': False,
            },
        ),
    ]
