# Generated by Django 5.2.15 on 2026-07-08 16:16

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0008_article_assembly_assemblycomponent_wagegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('entity', models.TextField()),
                ('entity_id', models.UUIDField()),
                ('from_status', models.TextField(blank=True, null=True)),
                ('to_status', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."status_change',
                'managed': False,
            },
        ),
    ]
