# Generated by Django 5.2.15 on 2026-07-08 17:54

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0010_invoice_invoiceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('template_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('label', models.TextField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow"."checklist_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('entry', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."project_log',
                'managed': False,
            },
        ),
    ]
