# Generated by Django 5.2.15 on 2026-07-08 18:28

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0011_checklist_checklistitem_projectlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('order_number', models.TextField(db_default=db_core.models.WorkOrderNumberDefault())),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('building_id', models.UUIDField(blank=True, null=True)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('asset_id', models.UUIDField(blank=True, null=True)),
                ('responsibility_scope', models.TextField()),
                ('status', models.TextField()),
                ('priority', models.TextField()),
                ('customer_reference', models.TextField(blank=True, null=True)),
                ('order_evidence_reference', models.TextField(blank=True, null=True)),
                ('authority_id', models.UUIDField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(db_default=models.Value(False))),
                ('responsibility_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_of_work_order_id', models.UUIDField(blank=True, null=True)),
                ('is_warranty_case', models.BooleanField(db_default=models.Value(False))),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."work_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderParty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('source', models.TextField()),
                ('source_reference_id', models.UUIDField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('is_primary', models.BooleanField(db_default=models.Value(False))),
                ('allocation_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."work_order_party',
                'managed': False,
            },
        ),
    ]
