# Generated by Django 5.2.15 on 2026-07-08 18:56

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0012_workorder_workorderparty'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceParty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('is_primary', models.BooleanField(db_default=models.Value(False))),
                ('allocation_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('liability_group', models.TextField(blank=True, null=True)),
                ('liability_basis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."invoice_party',
                'managed': False,
            },
        ),
    ]
