# Generated by Django 5.2.15 on 2026-07-09 06:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0014_jobassignment_materialentry_servicejob_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningLevel',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('days_after_due', models.IntegerField()),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."dunning_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DunningNotice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('issued_at', models.DateField()),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."dunning_notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('payment_type', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(db_default='EUR', max_length=3)),
                ('paid_at', models.DateField()),
                ('import_source', models.TextField()),
                ('external_reference', models.TextField()),
                ('imported_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."payment',
                'managed': False,
            },
        ),
    ]
