# Generated by Django 5.2.15 on 2026-07-09 08:57

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0016_maintenance_wartung'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('contract_number', models.TextField(db_default=db_core.models.MaintenanceContractNumberDefault())),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('start_date', models.DateField()),
                ('interval_kind', models.TextField()),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('fixed_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('due_action', models.TextField()),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."maintenance_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('due_date', models.DateField(blank=True, null=True)),
                ('action', models.TextField()),
                ('result_object_type', models.TextField(blank=True, null=True)),
                ('result_object_id', models.UUIDField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."maintenance_event',
                'managed': False,
            },
        ),
    ]
