# Generated by Django 5.2.15 on 2026-07-09 11:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0017_maintenancecontract_maintenanceevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSalePrice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_standard', models.BooleanField(db_default=models.Value(False))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."article_sale_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSupplierReference',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_system', models.TextField()),
                ('source_namespace', models.TextField()),
                ('supplier_article_number', models.TextField()),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('discount_group', models.TextField(blank=True, null=True)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('price_unit_code', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."article_supplier_reference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalePriceGroup',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('calc_basis', models.TextField()),
                ('operator', models.TextField()),
                ('percent_change', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('amount_change', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.TextField()),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."sale_price_group',
                'managed': False,
            },
        ),
    ]
