# Generated by Django 5.2.15 on 2026-07-09 14:16

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0019_hr_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('absence_type', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('half_day_start', models.BooleanField(db_default=models.Value(False))),
                ('half_day_end', models.BooleanField(db_default=models.Value(False))),
                ('days_count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."absence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('employee_number', models.TextField(db_default=db_core.models.EmployeeNumberDefault())),
                ('status', models.TextField()),
                ('hired_on', models.DateField()),
                ('left_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('hours_monday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_tuesday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_wednesday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_thursday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_friday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_saturday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_sunday', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vacation_days_per_year', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.TextField()),
                ('termination_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."employment_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacationBudget',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('entitlement_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carryover_days', models.DecimalField(db_default=models.Value(0), decimal_places=2, max_digits=5)),
                ('adjustment_days', models.DecimalField(db_default=models.Value(0), decimal_places=2, max_digits=5)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."vacation_budget',
                'managed': False,
            },
        ),
    ]
