# Generated by Django 5.2.15 on 2026-07-09 15:48

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0021_rechtematrix_hr_modul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'security"."role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('module', models.TextField()),
                ('action', models.TextField()),
                ('allowed', models.BooleanField()),
                ('row_scope', models.TextField()),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'security"."role_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'security"."user_role',
                'managed': False,
            },
        ),
    ]
