# Generated by Django 5.2.15 on 2026-07-09 20:49
# State-only-Migration (managed=False Models) für das company-Schema.
#
# HINWEIS (parallele Entwicklung): Ein weiterer Slice hat parallel die Migration
# `0025_resource_terminkategorie` erzeugt, die — wie `0025_mahnstufen_ausbau` —
# auf `0024_rechtematrix_company_modul` aufsetzt (zwei Zweige, zwei Leaf-Nodes).
# Diese ohnehin noch nicht angewandte State-only-Migration wird zum
# Vereinigungspunkt: Sie hängt an BEIDEN Zweigen und macht die Graph-Historie
# wieder linear (ein Leaf). Kein --merge-Extra-File, keine Umbenennung, keine
# Änderung an der Fremd-Migration nötig.

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0025_mahnstufen_ausbau'),
        ('db_core', '0025_resource_terminkategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('street', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.CharField(db_default='DE', max_length=2)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_default=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'company"."branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_singleton', models.BooleanField(db_default=True)),
                ('company_name', models.TextField()),
                ('legal_form', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('country', models.CharField(db_default='DE', max_length=2)),
                ('state_code', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('web', models.TextField(blank=True, null=True)),
                ('tax_number', models.TextField(blank=True, null=True)),
                ('vat_id', models.TextField(blank=True, null=True)),
                ('commercial_register', models.TextField(blank=True, null=True)),
                ('bank_name', models.TextField(blank=True, null=True)),
                ('iban', models.TextField(blank=True, null=True)),
                ('bic', models.TextField(blank=True, null=True)),
                ('managing_director', models.TextField(blank=True, null=True)),
                ('managing_director_title', models.TextField(blank=True, null=True)),
                ('default_language', models.CharField(db_default='de', max_length=2)),
                ('logo_file_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'company"."company_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('active', models.BooleanField(db_default=True)),
                ('sort_order', models.IntegerField(db_default=models.Value(0))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'company"."trade',
                'managed': False,
            },
        ),
    ]
