# Generated by Django 5.2.15 on 2026-07-09 20:57

import db_core.models
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0026_branch_companyprofile_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('color_token', models.TextField(db_default=models.Value('NAVY'))),
                ('status', models.TextField(db_default=models.Value('AKTIV'))),
                ('sort_order', models.IntegerField(db_default=models.Value(0))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."appointment_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobResource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'resource"."job_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('resource_number', models.TextField(db_default=db_core.models.ResourceNumberDefault())),
                ('name', models.TextField()),
                ('resource_type', models.TextField()),
                ('status', models.TextField(db_default=models.Value('AKTIV'))),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'resource"."resource',
                'managed': False,
            },
        ),
    ]
