# Generated by Django 5.2.15 on 2026-07-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # auf 0029 (State-only zu 0028) gezogen, damit die Vier-Augen-Models im
        # Graphen VOR dem Merge liegen und ein einziges Blatt bleibt.
        ('db_core', '0029_approvalrequest_foureyesaction'),
        ('db_core', '0032_rechtematrix_accounting_modul'),
    ]

    operations = [
    ]
