# Generated by Django 5.2.15 on 2026-07-10 05:26

import django.db.models.functions.datetime
from django.db import migrations, models

import db_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0033_merge_20260710_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('active', models.BooleanField(db_default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'accounting"."cost_center',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('account_number', models.TextField()),
                ('label', models.TextField()),
                ('account_type', models.TextField()),
                ('chart_of_accounts', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'accounting"."ledger_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('receipt_number', models.TextField(db_default=db_core.models.ReceiptNumberDefault())),
                ('supplier_invoice_number', models.TextField(blank=True, null=True)),
                ('receipt_date', models.DateField()),
                ('received_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(db_default='EUR', max_length=3)),
                ('net_total', models.DecimalField(db_default=0, decimal_places=2, max_digits=15)),
                ('tax_total', models.DecimalField(db_default=0, decimal_places=2, max_digits=15)),
                ('gross_total', models.DecimalField(db_default=0, decimal_places=2, max_digits=15)),
                ('status', models.TextField()),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'accounting"."receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position_number', models.IntegerField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('unit', models.TextField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'accounting"."receipt_line',
                'managed': False,
            },
        ),
    ]
