# Generated by Django 5.2.15 on 2026-07-10 07:18

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0036_beleg_positionsarten'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelegRubrik',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position_number', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."beleg_rubrik',
                'managed': False,
            },
        ),
    ]
