# Generated by Django 5.2.15 on 2026-07-10 12:21

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0039_artikel_listenpreis_nachkommastellen'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('storage_key', models.TextField(unique=True)),
                ('original_filename', models.TextField()),
                ('mime_type', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('media_metadata', models.JSONField(default=dict)),
                ('uploaded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'content"."file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(blank=True, null=True)),
                ('communication_id', models.UUIDField(blank=True, null=True)),
                ('link_category', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'content"."file_link',
                'managed': False,
            },
        ),
    ]
