# Generated by Django 5.2.15 on 2026-07-10 12:32

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0040_file_filelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierConnection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_system', models.TextField()),
                ('source_namespace', models.TextField()),
                ('label', models.TextField()),
                ('shop_url', models.TextField(blank=True, null=True)),
                ('credential_reference', models.TextField(blank=True, null=True)),
                ('status', models.TextField()),
                ('connection_kind', models.TextField()),
                ('last_import_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=1)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."supplier_connection',
                'managed': False,
            },
        ),
    ]
