# Generated by Django 5.2.15 on 2026-07-10 19:36

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0043_artikel_such_indizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('contact_type', models.TextField()),
                ('value', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'identity"."contact_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address_type', models.TextField()),
                ('is_primary', models.BooleanField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'identity"."party_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('relationship_type', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'identity"."party_relationship',
                'managed': False,
            },
        ),
    ]
