# Generated by Django 5.2.15 on 2026-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0044_contactpoint_partyaddress_partyrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCatalog',
            fields=[
                ('pk', models.CompositePrimaryKey('entity', 'status', blank=True, editable=False, primary_key=True, serialize=False)),
                ('entity', models.TextField()),
                ('status', models.TextField()),
                ('label', models.TextField()),
                ('sort_order', models.IntegerField()),
                ('is_initial', models.BooleanField()),
                ('is_final', models.BooleanField()),
                ('is_frozen', models.BooleanField()),
            ],
            options={
                'db_table': 'workflow"."status_catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('pk', models.CompositePrimaryKey('entity', 'from_status', 'to_status', blank=True, editable=False, primary_key=True, serialize=False)),
                ('entity', models.TextField()),
                ('from_status', models.TextField()),
                ('to_status', models.TextField()),
                ('requires_reason', models.BooleanField()),
            ],
            options={
                'db_table': 'workflow"."status_transition',
                'managed': False,
            },
        ),
    ]
