# Generated by Django 5.2.15 on 2026-07-10 21:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0046_mail_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('channel', models.TextField()),
                ('direction', models.TextField()),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('counterpart_party_id', models.UUIDField(blank=True, null=True)),
                ('counterpart_raw', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('recorded_by', models.UUIDField()),
                ('is_internal', models.BooleanField(db_default=False)),
                ('is_commercial', models.BooleanField(db_default=False)),
                ('assignment_status', models.TextField(db_default=models.Value('KLAERUNGSKORB'))),
                ('assignment_source', models.TextField(blank=True, null=True)),
                ('assignment_confirmed_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'content"."communication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('host', models.TextField()),
                ('port', models.IntegerField()),
                ('security', models.TextField()),
                ('username', models.TextField(blank=True, null=True)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('from_address', models.TextField()),
                ('from_name', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_default=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'company"."mail_account',
                'managed': False,
            },
        ),
    ]
