# Generated by Django 5.2.15 on 2026-07-11 09:15

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0049_akquisekanaele'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSource',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('active', models.BooleanField(db_default=True)),
                ('sort_order', models.IntegerField(db_default=models.Value(0))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'company"."acquisition_source',
                'managed': False,
            },
        ),
    ]
