# Generated by Django 5.2.15 on 2026-07-11 18:39

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0052_supplier_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCredential',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('customer_number', models.TextField(blank=True, null=True)),
                ('password_encrypted', models.BinaryField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."supplier_credential',
                'managed': False,
            },
        ),
    ]
