# Generated by Django 5.2.15 on 2026-07-11 20:28

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0054_site_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReport',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('weather', models.TextField(blank=True, null=True)),
                ('activity_text', models.TextField()),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('materials_note', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.TextField(db_default='ENTWURF')),
                ('signed_by_name', models.TextField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_file_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."site_report',
                'managed': False,
            },
        ),
    ]
