# Generated by Django 5.2.15 on 2026-07-11 21:19

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0056_punchout_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchoutSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('token_hash', models.TextField()),
                ('action', models.TextField()),
                ('status', models.TextField(db_default='OFFEN')),
                ('returned_cart_xml', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'pricing"."punchout_session',
                'managed': False,
            },
        ),
    ]
