# Generated by Django 5.2.15 on 2026-07-12 08:55

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0060_abschlag_schlussrechnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAdvance',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."invoice_advance',
                'managed': False,
            },
        ),
    ]
