# Generated by Django 5.2.15 on 2026-07-12 20:04

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0073_markuprule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('title', models.TextField()),
                ('due_date', models.DateField()),
                ('lead_time_days', models.IntegerField(db_default=models.Value(0))),
                ('status', models.TextField(db_default='OFFEN')),
                ('result_object_type', models.TextField(blank=True, null=True)),
                ('result_object_id', models.UUIDField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."due_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(blank=True, null=True)),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('start_date', models.DateField()),
                ('interval_kind', models.TextField()),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(db_default=models.Value(30))),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."inspection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('interval_kind', models.TextField()),
                ('interval_days', models.IntegerField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(db_default=models.Value(30))),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_suggestion', models.BooleanField(db_default=False)),
                ('is_active', models.BooleanField(db_default=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."inspection_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalAsset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('building_id', models.UUIDField(blank=True, null=True)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('name', models.TextField()),
                ('asset_type', models.TextField(blank=True, null=True)),
                ('attributes', models.JSONField(db_default={})),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."technical_asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('basis', models.TextField(db_default='BGB')),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('end_date', models.DateField()),
                ('lead_time_days', models.IntegerField(db_default=models.Value(90))),
                ('is_machinery', models.BooleanField(db_default=False)),
                ('status', models.TextField(db_default='AKTIV')),
                ('notes', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."warranty',
                'managed': False,
            },
        ),
    ]
