# Generated by Django 5.2.15 on 2026-07-13 08:47

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0078_qualifikationen_und_vorlagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentCategoryQualification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."appointment_category_qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(db_default=models.Value(True))),
                ('sort_order', models.IntegerField(db_default=models.Value(0))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."assignment_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignmentTemplateMember',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField(db_default='TECHNICIAN')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."assignment_template_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('evidence_note', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."employee_qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('label', models.TextField()),
                ('kind', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('expires', models.BooleanField(db_default=models.Value(False))),
                ('active', models.BooleanField(db_default=models.Value(True))),
                ('sort_order', models.IntegerField(db_default=models.Value(0))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."qualification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceJobQualification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."service_job_qualification',
                'managed': False,
            },
        ),
    ]
