# Generated by Django 5.2.15 on 2026-07-13 07:50

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0080_berichtspositionen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReportLine',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('position_number', models.IntegerField()),
                ('line_type', models.TextField()),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."site_report_line',
                'ordering': ['position_number'],
                'managed': False,
            },
        ),
    ]
