# Generated by Django 5.2.15 on 2026-07-13 16:27

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0084_abrechnungsbindung'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_kind', models.TextField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'invoicing"."billing_link',
                'managed': False,
            },
        ),
    ]
