# Generated by Django 5.2.15 on 2026-07-13 16:30

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0086_raumaufmass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('building_id', models.UUIDField(blank=True, null=True)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('storey', models.TextField(blank=True, null=True)),
                ('name', models.TextField()),
                ('room_type', models.TextField(blank=True, null=True)),
                ('floor_area_m2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('length_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('width_m', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('room_height_m', models.DecimalField(decimal_places=3, max_digits=8)),
                ('perimeter_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=13, null=True)),
                ('indoor_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('air_change_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('heat_load_w_per_m2', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('riser_distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.TextField(db_default='AKTIV')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomOpening',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('opening_type', models.TextField()),
                ('label', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(db_default=1)),
                ('width_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('height_m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('u_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."room_opening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSurface',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('surface_type', models.TextField()),
                ('adjacent', models.TextField()),
                ('orientation', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('gross_area_m2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('u_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('temp_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."room_surface',
                'managed': False,
            },
        ),
    ]
