# Generated by Django 5.2.15 on 2026-07-13 20:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0091_grundriss'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('name', models.TextField()),
                ('default_surface_type', models.TextField(blank=True, null=True)),
                ('default_opening_type', models.TextField(blank=True, null=True)),
                ('u_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.TextField(db_default='AKTIV')),
                ('sort_index', models.IntegerField(db_default=0)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."component_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomVertex',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('x_mm', models.IntegerField()),
                ('y_mm', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'property"."room_vertex',
                'ordering': ['idx'],
                'managed': False,
            },
        ),
    ]
