# Generated by Django 5.2.15 on 2026-07-14 16:25

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0103_belegung_und_verwaltung'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementMandate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mandate_type', models.TextField()),
                ('scope_type', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.TextField()),
                ('contract_reference', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(db_default=1)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'management"."management_mandate',
                'ordering': ['-valid_from'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementMandateUnit',
            fields=[
                ('pk', models.CompositePrimaryKey('mandate_id', 'unit_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'management"."management_mandate_unit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementResponsibility',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('responsibility_type', models.TextField()),
                ('priority', models.IntegerField(db_default=100)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'management"."management_responsibility',
                'ordering': ['priority', 'valid_from'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('occupancy_type', models.TextField()),
                ('contract_reference', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'tenure"."occupancy',
                'ordering': ['-valid_from'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OccupancyParty',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'tenure"."occupancy_party',
                'ordering': ['valid_from'],
                'managed': False,
            },
        ),
    ]
