# Generated by Django 5.2.15 on 2026-07-15 09:49

import django.contrib.postgres.fields
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0104_belegung_und_verwaltung_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProposal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('proposal_type', models.TextField()),
                ('target_type', models.TextField()),
                ('target_id', models.UUIDField()),
                ('target_version', models.IntegerField(blank=True, null=True)),
                ('proposed_payload', models.JSONField(default=dict)),
                ('payload_hash', models.TextField()),
                ('status', models.TextField(db_default='PENDING')),
                ('expires_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."ai_proposal',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('model_name', models.TextField()),
                ('model_version', models.TextField()),
                ('workflow_name', models.TextField()),
                ('workflow_version', models.TextField()),
                ('prompt_version', models.TextField()),
                ('permission_context', models.JSONField(default=dict)),
                ('sources', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result_status', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('resource_usage', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ai"."ai_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source_type', models.TextField()),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
                ('language', models.TextField(blank=True, null=True)),
                ('content_hash', models.TextField()),
                ('is_untrusted', models.BooleanField(db_default=models.Value(True))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."content_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding_model', models.TextField()),
                ('embedding_version', models.TextField()),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('content_hash', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."embedding',
                'ordering': ['chunk_index'],
                'managed': False,
            },
        ),
    ]
