# Generated by Django 5.2.15 on 2026-07-15 12:47

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0106_ki_tool_vertrag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tool_key', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('capability', models.TextField()),
                ('invocation_mode', models.TextField()),
                ('endpoint_url', models.TextField(blank=True, null=True)),
                ('credential_reference', models.TextField(blank=True, null=True)),
                ('data_boundary', models.TextField(db_default='LOCAL_ONLY')),
                ('timeout_seconds', models.IntegerField(db_default=models.Value(120))),
                ('max_attempts', models.IntegerField(db_default=models.Value(3))),
                ('backoff_seconds', models.DecimalField(db_default=models.Value(5), decimal_places=2, max_digits=8)),
                ('capability_version', models.TextField(db_default='1')),
                ('contract_version', models.TextField(db_default='1')),
                ('status', models.TextField(db_default='ACTIVE')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_health', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."tool',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('capability', models.TextField()),
                ('capability_version', models.TextField(db_default='1')),
                ('contract_version', models.TextField(db_default='1')),
                ('step_key', models.TextField()),
                ('status', models.TextField(db_default='QUEUED')),
                ('attempt', models.IntegerField(db_default=models.Value(0))),
                ('leased_until', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('request_hash', models.TextField(blank=True, null=True)),
                ('input_ref', models.JSONField(default=dict)),
                ('output_ref', models.JSONField(blank=True, null=True)),
                ('output_hash', models.TextField(blank=True, null=True)),
                ('is_untrusted', models.BooleanField(db_default=models.Value(True))),
                ('error_code', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('cost_units', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('cost_currency', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."tool_call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('workflow_name', models.TextField()),
                ('workflow_version', models.TextField()),
                ('status', models.TextField(db_default='QUEUED')),
                ('current_step', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai"."workflow_run',
                'managed': False,
            },
        ),
    ]
