# Generated by Django 5.2.15 on 2026-07-17 18:58

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0114_geraetetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('app_user_id', models.UUIDField(blank=True, null=True)),
                ('token_hash', models.TextField(unique=True)),
                ('device_name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'security"."device_token',
                'managed': False,
            },
        ),
    ]
