# Generated by Django 5.2.15 on 2026-07-18 20:52

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0117_ki_assistent_gespraech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField(db_default='')),
                ('status', models.TextField(db_default='ACTIVE')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."conversation',
                'ordering': ['-updated_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('role', models.TextField()),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('intent', models.TextField(blank=True, null=True)),
                ('proposal_id', models.UUIDField(blank=True, null=True)),
                ('aus_untrusted_quelle', models.BooleanField(db_default=models.Value(False))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'ai"."conversation_turn',
                'ordering': ['seq'],
                'managed': False,
            },
        ),
    ]
