# Generated by Django 5.2.15 on 2026-07-20 11:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0120_gewerk_fundament'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTrade',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'hr"."employee_trade',
                'managed': False,
            },
        ),
    ]
