# Generated by Django 5.2.15 on 2026-07-21 16:42

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0127_dateikategorien'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('label', models.TextField()),
                ('is_system', models.BooleanField(db_default=models.Value(False))),
                ('status', models.TextField(db_default=models.Value('AKTIV'))),
                ('sort_order', models.IntegerField(db_default=models.Value(100))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'content"."file_category',
                'managed': False,
            },
        ),
    ]
