# Generated by Django 5.2.15 on 2026-07-22 12:01

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0132_berichtskopf_einfrieren'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipInterest',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('share_numerator', models.IntegerField(blank=True, null=True)),
                ('share_denominator', models.IntegerField(blank=True, null=True)),
                ('ownership_type', models.TextField(db_default='CO_OWNER')),
                ('confirmation_status', models.TextField(db_default='UNCONFIRMED')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'tenure"."ownership_interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OwnershipPeriod',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('distribution_status', models.TextField(db_default='UNRESOLVED')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('source_type', models.TextField()),
                ('source_reference', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'tenure"."ownership_period',
                'ordering': ['-valid_from'],
                'managed': False,
            },
        ),
    ]
