# Generated by Django 5.2.15 on 2026-07-22 12:48

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0133_eigentum_modelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAuthority',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('authority_type', models.TextField()),
                ('scope_type', models.TextField(db_default='GENERAL')),
                ('amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('evidence_document_id', models.UUIDField(blank=True, null=True)),
                ('status', models.TextField(db_default='ACTIVE')),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'management"."party_authority',
                'ordering': ['-valid_from'],
                'managed': False,
            },
        ),
    ]
