# Generated by Django 5.2.15 on 2026-07-28 07:26

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0135_wartungsvertrag_anlagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceContractAsset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_default=models.Value(True))),
                ('version', models.IntegerField(db_default=models.Value(1))),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'maintenance"."contract_asset',
                'managed': False,
            },
        ),
    ]
