# Generated by Django 5.2.15 on 2026-07-31 10:22

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0137_aufgabe_dialog_und_benachrichtigung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('title', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('target_type', models.TextField()),
                ('target_id', models.UUIDField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'notify"."notification',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'workflow"."task_comment',
                'ordering': ['created_at', 'id'],
                'managed': False,
            },
        ),
    ]
