# Generated by Django 5.2.15 on 2026-07-31 20:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0141_oeffentliche_links_und_systemakteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('target_type', models.TextField()),
                ('target_id', models.UUIDField()),
                ('token_hash', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('single_use', models.BooleanField(db_default=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(db_default=0)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'security"."public_link',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
